
package differentia;

import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.concurrent.TimeUnit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;

/**
 *
 * @author macie
 */
public class Menu extends javax.swing.JFrame {

    public File img2;
    public File img1;
    static int he = 0;
    static int wid = 0;

    // public Comp compare = new Comp();
    public Copy copy = new Copy();

    /**
     * Creates new form Menu
     */
    public Menu() {

        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        attachButton1 = new javax.swing.JButton();
        PathField1 = new javax.swing.JTextField();
        attachButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPane2 = new javax.swing.JPanel();
        okButton = new javax.swing.JButton();
        JLabelImage1 = new javax.swing.JLabel();
        PathField2 = new javax.swing.JTextField();
        JLabelImage2 = new javax.swing.JLabel();
        logiTxt = new javax.swing.JTextField();
        JLabelImage3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(600, 600, 600, 600));
        setLocation(new java.awt.Point(400, 100));
        setMaximizedBounds(new java.awt.Rectangle(600, 600, 600, 600));
        setMaximumSize(new java.awt.Dimension(700, 600));
        setMinimumSize(new java.awt.Dimension(700, 600));
        setPreferredSize(new java.awt.Dimension(700, 600));

        attachButton1.setText("Attach");
        attachButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attachButton1ActionPerformed(evt);
            }
        });

        PathField1.setEditable(false);
        PathField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PathField1ActionPerformed(evt);
            }
        });

        attachButton2.setText("Attach");
        attachButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attachButton2ActionPerformed(evt);
            }
        });

        jLabel1.setText("Image #1");

        jLabel2.setText("Image #2");

        okButton.setText("Compere");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPane2Layout = new javax.swing.GroupLayout(jPane2);
        jPane2.setLayout(jPane2Layout);
        jPane2Layout.setHorizontalGroup(
            jPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPane2Layout.createSequentialGroup()
                .addContainerGap(276, Short.MAX_VALUE)
                .addComponent(okButton)
                .addContainerGap())
        );
        jPane2Layout.setVerticalGroup(
            jPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPane2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(okButton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(168, Short.MAX_VALUE))
        );

        PathField2.setEditable(false);
        PathField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PathField2ActionPerformed(evt);
            }
        });

        logiTxt.setEditable(false);
        logiTxt.setToolTipText("");
        logiTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logiTxtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(logiTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 573, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(JLabelImage1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(PathField1, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(attachButton1)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(JLabelImage2, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel2)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(PathField2, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(attachButton2)))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(368, 368, 368)
                    .addComponent(JLabelImage3, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE)
                    .addGap(73, 73, 73)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PathField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(attachButton1)
                    .addComponent(PathField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(attachButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JLabelImage1, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JLabelImage2, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(logiTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(110, 110, 110))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(72, 72, 72)
                    .addComponent(JLabelImage3, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(353, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PathField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PathField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PathField1ActionPerformed

    private void attachButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_attachButton1ActionPerformed
        try {
            JFileChooser chooser = new JFileChooser();
            chooser.showOpenDialog(null);
            img1 = chooser.getSelectedFile();

            String imagepath = img1.getCanonicalPath();

            PathField1.setText(imagepath);
            Path p = Paths.get(imagepath);
            Container.setFile1Name(p.getFileName().toString());

            System.out.println(p.getFileName().toString());

            imagepath = imagepath.replace('\\', '/');
            Container.setFile1Source(imagepath);
            BufferedImage imgbuf1 = null;
            try {
                imgbuf1 = ImageIO.read(new File(imagepath));
                he = imgbuf1.getHeight();
                wid = imgbuf1.getWidth();

                while (he > 245 || wid > 245) {
                    Double hed = he * 0.9;
                    Double widd = wid * 0.9;
                    he = hed.intValue();
                    wid = widd.intValue();
                }

            } catch (IOException e) {
                e.printStackTrace();
            }

            Image scaimg1 = imgbuf1.getScaledInstance(wid, he,
                    Image.SCALE_SMOOTH);

            JLabelImage1.setIcon(new ImageIcon(scaimg1));

        } catch (IOException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_attachButton1ActionPerformed

    private void PathField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PathField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PathField2ActionPerformed

    private void attachButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_attachButton2ActionPerformed
        try {
            JFileChooser chooser2 = new JFileChooser();
            chooser2.showOpenDialog(null);
            img2 = chooser2.getSelectedFile();

            String imagepath2 = img2.getCanonicalPath();
            System.out.println(imagepath2);
            PathField2.setText(imagepath2);

            Path p = Paths.get(imagepath2);
            Container.setFile2Name(p.getFileName().toString());
            imagepath2 = imagepath2.replace('\\', '/');
            System.out.println(imagepath2);
            Container.setFile2Source(imagepath2);

            BufferedImage imgbuf2 = null;
            try {
                imgbuf2 = ImageIO.read(new File(imagepath2));
                he = imgbuf2.getHeight();
                wid = imgbuf2.getWidth();

                while (he > 245 || wid > 245) {
                    Double hed = he * 0.9;
                    Double widd = wid * 0.9;
                    he = hed.intValue();
                    wid = widd.intValue();
                }

            } catch (IOException e) {
                e.printStackTrace();
            }

            Image scaimg2 = imgbuf2.getScaledInstance(wid, he,
                    Image.SCALE_SMOOTH);

            JLabelImage2.setIcon(new ImageIcon(scaimg2));
        } catch (IOException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_attachButton2ActionPerformed

    private void logiTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logiTxtActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_logiTxtActionPerformed

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed

        try {
            copy.Copy(img1, Container.getFile1Name());
        } catch (IOException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            TimeUnit.SECONDS.sleep(5);
        } catch (InterruptedException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            copy.Copy(img2, Container.getFile2Name());
        } catch (IOException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            TimeUnit.SECONDS.sleep(5);
        } catch (InterruptedException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
        //compare.start();
        Main main = new Main();
        try {
            main.main();
        } catch (IOException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_okButtonActionPerformed

    /**
     *
     * @param txt
     */
    public static void setLog(String txt) {
        logiTxt.setText(txt);

    }

    public static void main(String args[]) {

    
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }


       
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLabelImage1;
    private javax.swing.JLabel JLabelImage2;
    private javax.swing.JLabel JLabelImage3;
    private javax.swing.JTextField PathField1;
    private javax.swing.JTextField PathField2;
    private javax.swing.JButton attachButton1;
    private javax.swing.JButton attachButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPane2;
    public static javax.swing.JTextField logiTxt;
    private javax.swing.JButton okButton;
    // End of variables declaration//GEN-END:variables
}
